### ISSUE TITLE
`realpath` not a mac command

### ISSUE THREAD

**Issue by thebenlamm** [tkb-/glaciertools#2]
replace with readonly SCRIPT="$(dirname "$0")" ?

**Comment by numblr** [comment]
Thanks for the hint, seems I have it on my machine from some coreutils package..

I replaced it by `"$(cd $(dirname "$0"); pwd)"`, mainly for consistency with `multipart_upload.sh`, because I wanted the absolute path there (also for the file) as the script changes directory to store the temp files while uploading the parts.
